// DASHBOARD
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST'
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS'
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE'

// FLASH
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

// PORTAL
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST'
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'

export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST'
export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE'
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS'

export const PORTAL_CAPTCHA_CHANGE_REQUEST = 'PORTAL_CAPTCHA_CHANGE_REQUEST'
export const PORTAL_CAPTCHA_CHANGE_FAILURE = 'PORTAL_CAPTCHA_CHANGE_FAILURE'
export const PORTAL_CAPTCHA_CHANGE_SUCCESS = 'PORTAL_CAPTCHA_CHANGE_SUCCESS'

export const MODAL_ACCESSTOKEN = 'MODAL_ACCESSTOKEN'

export const LOGOUT_USER = 'LOGOUT_USER'

// Profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_FAILURE = 'PROFILE_FAILURE'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'

// SIGNIN
export const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST'
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE'
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'

// Consumer
export const CONSUMER_REQUEST = 'CONSUMER_REQUEST'
export const CONSUMER_SUCCESS = 'CONSUMER_SUCCESS'
export const CONSUMER_FAILURE = 'CONSUMER_FAILURE'

export const CONSUMER_ID_REQUEST = 'CONSUMER_ID_REQUEST'
export const CONSUMER_ID_SUCCESS = 'CONSUMER_ID_SUCCESS'
export const CONSUMER_ID_FAILURE = 'CONSUMER_ID_FAILURE'

export const CONSUMER_SUSPEND_REQUEST = 'CONSUMER_SUSPEND_REQUEST'
export const CONSUMER_SUSPEND_SUCCESS = 'CONSUMER_SUSPEND_SUCCESS'
export const CONSUMER_SUSPEND_FAILURE = 'CONSUMER_SUSPEND_FAILURE'

// Consumer Villa
export const CONSUMER_VILLA_REQUEST = 'CONSUMER_VILLA_REQUEST'
export const CONSUMER_VILLA_SUCCESS = 'CONSUMER_VILLA_SUCCESS'
export const CONSUMER_VILLA_FAILURE = 'CONSUMER_VILLA_FAILURE'

export const CONSUMER_VILLA_ID_REQUEST = 'CONSUMER_VILLA_ID_REQUEST'
export const CONSUMER_VILLA_ID_SUCCESS = 'CONSUMER_VILLA_ID_SUCCESS'
export const CONSUMER_VILLA_ID_FAILURE = 'CONSUMER_VILLA_ID_FAILURE'

export const CONSUMER_VILLA_SUSPEND_REQUEST = 'CONSUMER_VILLA_SUSPEND_REQUEST'
export const CONSUMER_VILLA_SUSPEND_SUCCESS = 'CONSUMER_VILLA_SUSPEND_SUCCESS'
export const CONSUMER_VILLA_SUSPEND_FAILURE = 'CONSUMER_VILLA_SUSPEND_FAILURE'

// Account
export const CREATE_PASSWORD_REQUEST = 'CREATE_PASSWORD_REQUEST'
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS'
export const CREATE_PASSWORD_FAILURE = 'CREATE_PASSWORD_FAILURE'

// TRANSACTIONS
export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS'
export const TRANSACTIONS_FAILURE = 'TRANSACTIONS_FAILURE'

export const SEARCH_TRANSACTIONS_BY_ID_REQUEST = 'SEARCH_TRANSACTIONS_BY_ID_REQUEST'
export const SEARCH_TRANSACTIONS_BY_ID_SUCCESS = 'SEARCH_TRANSACTIONS_BY_ID_SUCCESS'
export const SEARCH_TRANSACTIONS_BY_ID_FAILURE = 'SEARCH_TRANSACTIONS_BY_ID_FAILURE'

export const VOID_TRANSACTIONS_REQUEST = 'VOID_TRANSACTIONS_REQUEST'
export const VOID_TRANSACTIONS_SUCCESS = 'VOID_TRANSACTIONS_SUCCESS'
export const VOID_TRANSACTIONS_FAILURE = 'VOID_TRANSACTIONS_FAILURE'

export const EXPORT_TRANSACTIONS_REQUEST = 'EXPORT_TRANSACTIONS_REQUEST'
export const EXPORT_TRANSACTIONS_SUCCESS = 'EXPORT_TRANSACTIONS_SUCCESS'
export const EXPORT_TRANSACTIONS_FAILURE = 'EXPORT_TRANSACTIONS_FAILURE'

// MERCHANTS
export const LOAD_MERCHANTS_REQUEST = 'LOAD_MERCHANTS_REQUEST'
export const LOAD_MERCHANTS_SUCCESS = 'LOAD_MERCHANTS_SUCCESS'
export const LOAD_MERCHANTS_FAILURE = 'LOAD_MERCHANTS_FAILURE'

export const SEARCH_MERCHANTS_REQUEST = 'SEARCH_MERCHANTS_REQUEST'
export const SEARCH_MERCHANTS_SUCCESS = 'SEARCH_MERCHANTS_SUCCESS'
export const SEARCH_MERCHANTS_FAILURE = 'SEARCH_MERCHANTS_FAILURE'

export const SEARCH_MERCHANTS_NAME_REQUEST = 'SEARCH_MERCHANTS_NAME_REQUEST'
export const SEARCH_MERCHANTS_NAME_SUCCESS = 'SEARCH_MERCHANTS_NAME_SUCCESS'
export const SEARCH_MERCHANTS_NAME_FAILURE = 'SEARCH_MERCHANTS_NAME_FAILURE'

export const SEARCH_MERCHANTS_ID_REQUEST = 'SEARCH_MERCHANTS_ID_REQUEST'
export const SEARCH_MERCHANTS_ID_SUCCESS = 'SEARCH_MERCHANTS_ID_SUCCESS'
export const SEARCH_MERCHANTS_ID_FAILURE = 'SEARCH_MERCHANTS_ID_FAILURE'

export const LOAD_MERCHANTS_TYPE_REQUEST = 'LOAD_MERCHANTS_TYPE_REQUEST'
export const LOAD_MERCHANTS_TYPE_SUCCESS = 'LOAD_MERCHANTS_TYPE_SUCCESS'
export const LOAD_MERCHANTS_TYPE_FAILURE = 'LOAD_MERCHANTS_TYPE_FAILURE'

export const LOAD_MERCHANTS_DEVICELOCK_REQUEST = 'LOAD_MERCHANTS_DEVICELOCK_REQUEST'
export const LOAD_MERCHANTS_DEVICELOCK_SUCCESS = 'LOAD_MERCHANTS_DEVICELOCK_SUCCESS'
export const LOAD_MERCHANTS_DEVICELOCK_FAILURE = 'LOAD_MERCHANTS_DEVICELOCK_FAILURE'

export const LOAD_MERCHANTS_DEVICEUNLOCK_REQUEST = 'LOAD_MERCHANTS_DEVICEUNLOCK_REQUEST'
export const LOAD_MERCHANTS_DEVICEUNLOCK_SUCCESS = 'LOAD_MERCHANTS_DEVICEUNLOCK_SUCCESS'
export const LOAD_MERCHANTS_DEVICEUNLOCK_FAILURE = 'LOAD_MERCHANTS_DEVICEUNLOCK_FAILURE'

export const MERCHANTS_SUSPEND_REQUEST = 'MERCHANTS_SUSPEND_REQUEST'
export const MERCHANTS_SUSPEND_SUCCESS = 'MERCHANTS_SUSPEND_SUCCESS'
export const MERCHANTS_SUSPEND_FAILURE = 'MERCHANTS_SUSPEND_FAILURE'

export const MERCHANTS_RESETPIN_REQUEST = 'MERCHANTS_RESETPIN_REQUEST'
export const MERCHANTS_RESETPIN_SUCCESS = 'MERCHANTS_RESETPIN_SUCCESS'
export const MERCHANTS_RESETPIN_FAILURE = 'MERCHANTS_RESETPIN_FAILURE'

export const MERCHANTS_RESETQANDA_REQUEST = 'MERCHANTS_RESETQANDA_REQUEST'
export const MERCHANTS_RESETQANDA_SUCCESS = 'MERCHANTS_RESETQANDA_SUCCESS'
export const MERCHANTS_RESETQANDA_FAILURE = 'MERCHANTS_RESETQANDA_FAILURE'

export const MERCHANTS_UPDATE_REQUEST = 'MERCHANTS_UPDATE_REQUEST'
export const MERCHANTS_UPDATE_SUCCESS = 'MERCHANTS_UPDATE_SUCCESS'
export const MERCHANTS_UPDATE_FAILURE = 'MERCHANTS_UPDATE_FAILURE'

// MERCHANTS_VILLA VILLA
export const LOAD_MERCHANTS_VILLA_REQUEST = 'LOAD_MERCHANTS_VILLA_REQUEST'
export const LOAD_MERCHANTS_VILLA_SUCCESS = 'LOAD_MERCHANTS_VILLA_SUCCESS'
export const LOAD_MERCHANTS_VILLA_FAILURE = 'LOAD_MERCHANTS_VILLA_FAILURE'

export const SEARCH_MERCHANTS_VILLA_REQUEST = 'SEARCH_MERCHANTS_VILLA_REQUEST'
export const SEARCH_MERCHANTS_VILLA_SUCCESS = 'SEARCH_MERCHANTS_VILLA_SUCCESS'
export const SEARCH_MERCHANTS_VILLA_FAILURE = 'SEARCH_MERCHANTS_VILLA_FAILURE'

export const SEARCH_MERCHANTS_VILLA_NAME_REQUEST = 'SEARCH_MERCHANTS_VILLA_NAME_REQUEST'
export const SEARCH_MERCHANTS_VILLA_NAME_SUCCESS = 'SEARCH_MERCHANTS_VILLA_NAME_SUCCESS'
export const SEARCH_MERCHANTS_VILLA_NAME_FAILURE = 'SEARCH_MERCHANTS_VILLA_NAME_FAILURE'

export const SEARCH_MERCHANTS_VILLA_ID_REQUEST = 'SEARCH_MERCHANTS_VILLA_ID_REQUEST'
export const SEARCH_MERCHANTS_VILLA_ID_SUCCESS = 'SEARCH_MERCHANTS_VILLA_ID_SUCCESS'
export const SEARCH_MERCHANTS_VILLA_ID_FAILURE = 'SEARCH_MERCHANTS_VILLA_ID_FAILURE'

export const LOAD_MERCHANTS_VILLA_TYPE_REQUEST = 'LOAD_MERCHANTS_VILLA_TYPE_REQUEST'
export const LOAD_MERCHANTS_VILLA_TYPE_SUCCESS = 'LOAD_MERCHANTS_VILLA_TYPE_SUCCESS'
export const LOAD_MERCHANTS_VILLA_TYPE_FAILURE = 'LOAD_MERCHANTS_VILLA_TYPE_FAILURE'

export const LOAD_MERCHANTS_VILLA_DEVICELOCK_REQUEST = 'LOAD_MERCHANTS_VILLA_DEVICELOCK_REQUEST'
export const LOAD_MERCHANTS_VILLA_DEVICELOCK_SUCCESS = 'LOAD_MERCHANTS_VILLA_DEVICELOCK_SUCCESS'
export const LOAD_MERCHANTS_VILLA_DEVICELOCK_FAILURE = 'LOAD_MERCHANTS_VILLA_DEVICELOCK_FAILURE'

export const LOAD_MERCHANTS_VILLA_DEVICEUNLOCK_REQUEST = 'LOAD_MERCHANTS_VILLA_DEVICEUNLOCK_REQUEST'
export const LOAD_MERCHANTS_VILLA_DEVICEUNLOCK_SUCCESS = 'LOAD_MERCHANTS_VILLA_DEVICEUNLOCK_SUCCESS'
export const LOAD_MERCHANTS_VILLA_DEVICEUNLOCK_FAILURE = 'LOAD_MERCHANTS_VILLA_DEVICEUNLOCK_FAILURE'

export const MERCHANTS_VILLA_SUSPEND_REQUEST = 'MERCHANTS_VILLA_SUSPEND_REQUEST'
export const MERCHANTS_VILLA_SUSPEND_SUCCESS = 'MERCHANTS_VILLA_SUSPEND_SUCCESS'
export const MERCHANTS_VILLA_SUSPEND_FAILURE = 'MERCHANTS_VILLA_SUSPEND_FAILURE'

export const MERCHANTS_VILLA_RESETPIN_REQUEST = 'MERCHANTS_VILLA_RESETPIN_REQUEST'
export const MERCHANTS_VILLA_RESETPIN_SUCCESS = 'MERCHANTS_VILLA_RESETPIN_SUCCESS'
export const MERCHANTS_VILLA_RESETPIN_FAILURE = 'MERCHANTS_VILLA_RESETPIN_FAILURE'

export const MERCHANTS_VILLA_RESETQANDA_REQUEST = 'MERCHANTS_VILLA_RESETQANDA_REQUEST'
export const MERCHANTS_VILLA_RESETQANDA_SUCCESS = 'MERCHANTS_VILLA_RESETQANDA_SUCCESS'
export const MERCHANTS_VILLA_RESETQANDA_FAILURE = 'MERCHANTS_VILLA_RESETQANDA_FAILURE'

export const MERCHANTS_VILLA_UPDATE_REQUEST = 'MERCHANTS_VILLA_UPDATE_REQUEST'
export const MERCHANTS_VILLA_UPDATE_SUCCESS = 'MERCHANTS_VILLA_UPDATE_SUCCESS'
export const MERCHANTS_VILLA_UPDATE_FAILURE = 'MERCHANTS_VILLA_UPDATE_FAILURE'

// AGENTS
export const LOAD_AGENTS_REQUEST = 'LOAD_AGENTS_REQUEST'
export const LOAD_AGENTS_SUCCESS = 'LOAD_AGENTS_SUCCESS'
export const LOAD_AGENTS_FAILURE = 'LOAD_AGENTS_FAILURE'

export const SEARCH_AGENTS_REQUEST = 'SEARCH_AGENTS_REQUEST'
export const SEARCH_AGENTS_SUCCESS = 'SEARCH_AGENTS_SUCCESS'
export const SEARCH_AGENTS_FAILURE = 'SEARCH_AGENTS_FAILURE'

// PROMOTIONS
export const LOAD_PROMOTIONS_REQUEST = 'LOAD_PROMOTIONS_REQUEST'
export const LOAD_PROMOTIONS_SUCCESS = 'LOAD_PROMOTIONS_SUCCESS'
export const LOAD_PROMOTIONS_FAILURE = 'LOAD_PROMOTIONS_FAILURE'

export const SEARCH_PROMOTIONS_REQUEST = 'SEARCH_PROMOTIONS_REQUEST'
export const SEARCH_PROMOTIONS_SUCCESS = 'SEARCH_PROMOTIONS_SUCCESS'
export const SEARCH_PROMOTIONS_FAILURE = 'SEARCH_PROMOTIONS_FAILURE'

// STAFFS
export const LOAD_STAFFS_REQUEST = 'LOAD_STAFFS_REQUEST'
export const LOAD_STAFFS_SUCCESS = 'LOAD_STAFFS_SUCCESS'
export const LOAD_STAFFS_FAILURE = 'LOAD_STAFFS_FAILURE'

export const SEARCH_STAFFS_REQUEST = 'SEARCH_STAFFS_REQUEST'
export const SEARCH_STAFFS_SUCCESS = 'SEARCH_STAFFS_SUCCESS'
export const SEARCH_STAFFS_FAILURE = 'SEARCH_STAFFS_FAILURE'

// REPORT
export const REPORT_PAYMENT_REQUEST = 'REPORT_PAYMENT_REQUEST'
export const REPORT_PAYMENT_SUCCESS = 'REPORT_PAYMENT_SUCCESS'
export const REPORT_PAYMENT_FAILURE = 'REPORT_PAYMENT_FAILURE'

export const REPORT_SUMMARY_WALLET_REQUEST = 'REPORT_SUMMARY_WALLET_REQUEST'
export const REPORT_SUMMARY_WALLET_SUCCESS = 'REPORT_SUMMARY_WALLET_SUCCESS'
export const REPORT_SUMMARY_WALLET_FAILURE = 'REPORT_SUMMARY_WALLET_FAILURE'

// SKYLANE
export const REPORT_SKYLANE_PAYMENT_REQUEST = 'REPORT_SKYLANE_PAYMENT_REQUEST'
export const REPORT_SKYLANE_PAYMENT_SUCCESS = 'REPORT_SKYLANE_PAYMENT_SUCCESS'
export const REPORT_SKYLANE_PAYMENT_FAILURE = 'REPORT_SKYLANE_PAYMENT_FAILURE'

export const REPORT_SKYLANE_TOPUP_REQUEST = 'REPORT_SKYLANE_TOPUP_REQUEST'
export const REPORT_SKYLANE_TOPUP_SUCCESS = 'REPORT_SKYLANE_TOPUP_SUCCESS'
export const REPORT_SKYLANE_TOPUP_FAILURE = 'REPORT_SKYLANE_TOPUP_FAILURE'

export const REPORT_SKYLANE_SUMMARY_CONSUMER_REQUEST = 'REPORT_SKYLANE_SUMMARY_CONSUMER_REQUEST'
export const REPORT_SKYLANE_SUMMARY_CONSUMER_SUCCESS = 'REPORT_SKYLANE_SUMMARY_CONSUMER_SUCCESS'
export const REPORT_SKYLANE_SUMMARY_CONSUMER_FAILURE = 'REPORT_SKYLANE_SUMMARY_CONSUMER_FAILURE'

export const REPORT_SKYLANE_SUMMARY_SETTLE_REQUEST = 'REPORT_SKYLANE_SUMMARY_SETTLE_REQUEST'
export const REPORT_SKYLANE_SUMMARY_SETTLE_SUCCESS = 'REPORT_SKYLANE_SUMMARY_SETTLE_SUCCESS'
export const REPORT_SKYLANE_SUMMARY_SETTLE_FAILURE = 'REPORT_SKYLANE_SUMMARY_SETTLE_FAILURE'

export const REPORT_SKYLANE_SUMMARY_MERCHANT_REQUEST = 'REPORT_SKYLANE_SUMMARY_MERCHANT_REQUEST'
export const REPORT_SKYLANE_SUMMARY_MERCHANT_SUCCESS = 'REPORT_SKYLANE_SUMMARY_MERCHANT_SUCCESS'
export const REPORT_SKYLANE_SUMMARY_MERCHANT_FAILURE = 'REPORT_SKYLANE_SUMMARY_MERCHANT_FAILURE'

export const REPORT_SKYLANE_SUMMARY_TERMINAL_REQUEST = 'REPORT_SKYLANE_SUMMARY_TERMINAL_REQUEST'
export const REPORT_SKYLANE_SUMMARY_TERMINAL_SUCCESS = 'REPORT_SKYLANE_SUMMARY_TERMINAL_SUCCESS'
export const REPORT_SKYLANE_SUMMARY_TERMINAL_FAILURE = 'REPORT_SKYLANE_SUMMARY_TERMINAL_FAILURE'

export const REPORT_SKYLANE_SUMMARY_TERMINAL_EDC_REQUEST = 'REPORT_SKYLANE_SUMMARY_TERMINAL_EDC_REQUEST'
export const REPORT_SKYLANE_SUMMARY_TERMINAL_EDC_SUCCESS = 'REPORT_SKYLANE_SUMMARY_TERMINAL_EDC_SUCCESS'
export const REPORT_SKYLANE_SUMMARY_TERMINAL_EDC_FAILURE = 'REPORT_SKYLANE_SUMMARY_TERMINAL_EDC_FAILURE'

export const REPORT_SKYLANE_TRANSACTION_UNMATCHED_REQUEST = 'REPORT_SKYLANE_TRANSACTION_UNMATCHED_REQUEST'
export const REPORT_SKYLANE_TRANSACTION_UNMATCHED_SUCCESS = 'REPORT_SKYLANE_TRANSACTION_UNMATCHED_SUCCESS'
export const REPORT_SKYLANE_TRANSACTION_UNMATCHED_FAILURE = 'REPORT_SKYLANE_TRANSACTION_UNMATCHED_FAILURE'

export const REPORT_SKYLANE_BALANCING_REQUEST = 'REPORT_SKYLANE_BALANCING_REQUEST'
export const REPORT_SKYLANE_BALANCING_SUCCESS = 'REPORT_SKYLANE_BALANCING_SUCCESS'
export const REPORT_SKYLANE_BALANCING_FAILURE = 'REPORT_SKYLANE_BALANCING_FAILURE'

// LANGUAGE
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE'
export const LOCALSTORAGE_LANGUAGE = 'SWITCH_LANGUAGE'

// error
export const ERROR_ADD_MESSAGE = 'ERROR_ADD_MESSAGE'

// the mall
export const THEMALL_GET_TIME_CLOSE_SHOP_REQUEST = 'THEMALL_GET_TIME_CLOSE_SHOP_REQUEST'
export const THEMALL_GET_TIME_CLOSE_SHOP_SUCCESS = 'THEMALL_GET_TIME_CLOSE_SHOP_SUCCESS'
export const THEMALL_GET_TIME_CLOSE_SHOP_FAILURE = 'THEMALL_GET_TIME_CLOSE_SHOP_FAILURE'

export const THEMALL_UPDATE_TIME_CLOSE_SHOP_REQUEST = 'THEMALL_UPDATE_TIME_CLOSE_SHOP_REQUEST'
export const THEMALL_UPDATE_TIME_CLOSE_SHOP_SUCCESS = 'THEMALL_UPDATE_TIME_CLOSE_SHOP_SUCCESS'
export const THEMALL_UPDATE_TIME_CLOSE_SHOP_FAILURE = 'THEMALL_UPDATE_TIME_CLOSE_SHOP_FAILURE'

export const THEMALL_TAXINVOICE_SEARCH_REQUEST = 'THEMALL_TAXINVOICE_SEARCH_REQUEST'
export const THEMALL_TAXINVOICE_SEARCH_SUCCESS = 'THEMALL_TAXINVOICE_SEARCH_SUCCESS'
export const THEMALL_TAXINVOICE_SEARCH_FAILURE = 'THEMALL_TAXINVOICE_SEARCH_FAILURE'

export const THEMALL_TAX_INVOICE_CREATE_REQUEST = 'THEMALL_TAX_INVOICE_CREATE_REQUEST'
export const THEMALL_TAX_INVOICE_CREATE_SUCCESS = 'THEMALL_TAX_INVOICE_CREATE_SUCCESS'
export const THEMALL_TAX_INVOICE_CREATE_FAILURE = 'THEMALL_TAX_INVOICE_CREATE_FAILURE'

export const THEMALL_TAX_INVOICE_SHOW_DETAIL_REQUEST = 'THEMALL_TAX_INVOICE_SHOW_DETAIL_REQUEST'
export const THEMALL_TAX_INVOICE_SHOW_DETAIL_SUCCESS = 'THEMALL_TAX_INVOICE_SHOW_DETAIL_SUCCESS'
export const THEMALL_TAX_INVOICE_SHOW_DETAIL_FAILURE = 'THEMALL_TAX_INVOICE_SHOW_DETAIL_FAILURE'

export const THEMALL_TAX_INVOICE_UPDATE_REQUEST = 'THEMALL_TAX_INVOICE_UPDATE_REQUEST'
export const THEMALL_TAX_INVOICE_UPDATE_SUCCESS = 'THEMALL_TAX_INVOICE_UPDATE_SUCCESS'
export const THEMALL_TAX_INVOICE_UPDATE_FAILURE = 'THEMALL_TAX_INVOICE_UPDATE_FAILURE'

export const THEMALL_TAXINVOICE_SEARCH_VIEW_REQUEST = 'THEMALL_TAXINVOICE_SEARCH_VIEW_REQUEST'
export const THEMALL_TAXINVOICE_SEARCH_VIEW_SUCCESS = 'THEMALL_TAXINVOICE_SEARCH_VIEW_SUCCESS'
export const THEMALL_TAXINVOICE_SEARCH_VIEW_FAILURE = 'THEMALL_TAXINVOICE_SEARCH_VIEW_FAILURE'

export const THEMALL_TAXINVOICE_REPRINT_REQUEST = 'THEMALL_TAXINVOICE_REPRINT_REQUEST'
export const THEMALL_TAXINVOICE_REPRINT_SUCCESS = 'THEMALL_TAXINVOICE_REPRINT_SUCCESS'
export const THEMALL_TAXINVOICE_REPRINT_FAILURE = 'THEMALL_TAXINVOICE_REPRINT_FAILURE'

export const THEMALL_REPORT_REQUEST = 'THEMALL_REPORT_REQUEST'
export const THEMALL_REPORT_SUCCESS = 'THEMALL_REPORT_SUCCESS'
export const THEMALL_REPORT_FAILURE = 'THEMALL_REPORT_FAILURE'

export const THEMALL_REPORT_PAYMENT_REQUEST = 'THEMALL_REPORT_PAYMENT_REQUEST'
export const THEMALL_REPORT_PAYMENT_SUCCESS = 'THEMALL_REPORT_PAYMENT_SUCCESS'
export const THEMALL_REPORT_PAYMENT_FAILURE = 'THEMALL_REPORT_PAYMENT_FAILURE'

export const THEMALL_PRODUCT_REQUEST = 'THEMALL_PRODUCT_REQUEST'
export const THEMALL_PRODUCT_SUCCESS = 'THEMALL_PRODUCT_SUCCESS'
export const THEMALL_PRODUCT_FAILURE = 'THEMALL_PRODUCT_FAILURE'

export const THEMALL_REPORT_PAYMENTALL_REQUEST = 'THEMALL_REPORT_PAYMENTALL_REQUEST'
export const THEMALL_REPORT_PAYMENTALL_SUCCESS = 'THEMALL_REPORT_PAYMENTALL_SUCCESS'
export const THEMALL_REPORT_PAYMENTALL_FAILURE = 'THEMALL_REPORT_PAYMENTALL_FAILURE'

export const THEMALL_REPORT_PAYMENTUNKNOWN_REQUEST = 'THEMALL_REPORT_PAYMENTUNKNOWN_REQUEST'
export const THEMALL_REPORT_PAYMENTUNKNOWN_SUCCESS = 'THEMALL_REPORT_PAYMENTUNKNOWN_SUCCESS'
export const THEMALL_REPORT_PAYMENTUNKNOWN_FAILURE = 'THEMALL_REPORT_PAYMENTUNKNOWN_FAILURE'

export const THEMALL_REPORT_PAYMENT_EXPORT_REQUEST = 'THEMALL_REPORT_PAYMENT_EXPORT_REQUEST'
export const THEMALL_REPORT_PAYMENT_EXPORT_SUCCESS = 'THEMALL_REPORT_PAYMENT_EXPORT_SUCCESS'
export const THEMALL_REPORT_PAYMENT_EXPORT_FAILURE = 'THEMALL_REPORT_PAYMENT_EXPORT_FAILURE'

export const THEMALL_SLIP_REQUEST = 'THEMALL_SLIP_REQUEST'
export const THEMALL_SLIP_SUCCESS = 'THEMALL_SLIP_SUCCESS'
export const THEMALL_SLIP_FAILURE = 'THEMALL_SLIP_FAILURE'

export const THEMALL_CLOSING_REQUEST = 'THEMALL_CLOSING_REQUEST'
export const THEMALL_CLOSING_SUCCESS = 'THEMALL_CLOSING_SUCCESS'
export const THEMALL_CLOSING_FAILURE = 'THEMALL_CLOSING_FAILURE'

export const THEMALL_RUNCLOSING_REQUEST = 'THEMALL_CLOSING_REQUEST'
export const THEMALL_RUNCLOSING_SUCCESS = 'THEMALL_CLOSING_SUCCESS'
export const THEMALL_RUNCLOSING_FAILURE = 'THEMALL_CLOSING_FAILURE'

export const THEMALL_GET_ALL_BRANCH_REQUEST = 'THEMALL_GET_ALL_BRANCH_REQUEST'
export const THEMALL_GET_ALL_BRANCH_FAILURE = 'THEMALL_GET_ALL_BRANCH_FAILURE'
export const THEMALL_GET_ALL_BRANCH_SUCCESS = 'THEMALL_GET_ALL_BRANCH_SUCCESS'

// VILLA
// TRANSACTIONS
export const TRANSACTIONS_VILLA_REQUEST = 'TRANSACTIONS_VILLA_REQUEST'
export const TRANSACTIONS_VILLA_SUCCESS = 'TRANSACTIONS_VILLA_SUCCESS'
export const TRANSACTIONS_VILLA_FAILURE = 'TRANSACTIONS_VILLA_FAILURE'

export const TAXINVOICE_CLOSING = 'TAXINVOICE_CLOSING'

export const TAXINVOICE_CLOSING_REQUEST = 'TAXINVOICE_CLOSING_REQUEST'
export const TAXINVOICE_CLOSING_SUCCESS = 'TAXINVOICE_CLOSING_SUCCESS'
export const TAXINVOICE_CLOSING_FAILURE = 'TAXINVOICE_CLOSING_FAILURE'

export const TAXINVOICE_SHORT_REQUEST = 'TAXINVOICE_SHORT_REQUEST'
export const TAXINVOICE_SHORT_SUCCESS = 'TAXINVOICE_SHORT_SUCCESS'
export const TAXINVOICE_SHORT_FAILURE = 'TAXINVOICE_SHORT_FAILURE'

export const THEMALL_REPORT_EXPORTS_LIST_REQUEST = 'THEMALL_REPORT_EXPORTS_LIST_REQUEST'
export const THEMALL_REPORT_EXPORTS_LIST_SUCCESS = 'THEMALL_REPORT_EXPORTS_LIST_SUCCESS'
export const THEMALL_REPORT_EXPORTS_LIST_FAILURE = 'THEMALL_REPORT_EXPORTS_LIST_FAILURE'
